// FIFA World Cup 2026 Annex C third-place assignment lookup.
export const ANNEX_C_WINNERS = ["A", "B", "D", "E", "G", "I", "K", "L"];

export const ANNEX_C_ROWS = [
  "EJIFHGLK",
  "HGIDJFLK",
  "EJIDHGLK",
  "EJIDHFLK",
  "EGIDJFLK",
  "EGJDHFLK",
  "EGIDHFLK",
  "EGJDHFLI",
  "EGJDHFIK",
  "HGICJFLK",
  "EJICHGLK",
  "EJICHFLK",
  "EGICJFLK",
  "EGJCHFLK",
  "EGICHFLK",
  "EGJCHFLI",
  "EGJCHFIK",
  "HGICJDLK",
  "CJIDHFLK",
  "CGIDJFLK",
  "CGJDHFLK",
  "CGIDHFLK",
  "CGJDHFLI",
  "CGJDHFIK",
  "EJICHDLK",
  "EGICJDLK",
  "EGJCHDLK",
  "EGICHDLK",
  "EGJCHDLI",
  "EGJCHDIK",
  "CJEDIFLK",
  "CJEDHFLK",
  "CEIDHFLK",
  "CJEDHFLI",
  "CJEDHFIK",
  "CGEDJFLK",
  "CGEDIFLK",
  "CGEDJFLI",
  "CGEDJFIK",
  "CGEDHFLK",
  "CGJDHFLE",
  "CGJDHFEK",
  "CGEDHFLI",
  "CGEDHFIK",
  "CGJDHFEI",
  "HJBFIGLK",
  "EJIBHGLK",
  "EJBFIHLK",
  "EJBFIGLK",
  "EJBFHGLK",
  "EGBFIHLK",
  "EJBFHGLI",
  "EJBFHGIK",
  "HJBDIGLK",
  "HJBDIFLK",
  "IGBDJFLK",
  "HGBDJFLK",
  "HGBDIFLK",
  "HGBDJFLI",
  "HGBDJFIK",
  "EJBDIHLK",
  "EJBDIGLK",
  "EJBDHGLK",
  "EGBDIHLK",
  "EJBDHGLI",
  "EJBDHGIK",
  "EJBDIFLK",
  "EJBDHFLK",
  "EIBDHFLK",
  "EJBDHFLI",
  "EJBDHFIK",
  "EGBDJFLK",
  "EGBDIFLK",
  "EGBDJFLI",
  "EGBDJFIK",
  "EGBDHFLK",
  "HGBDJFLE",
  "HGBDJFEK",
  "EGBDHFLI",
  "EGBDHFIK",
  "HGBDJFEI",
  "HJBCIGLK",
  "HJBCIFLK",
  "IGBCJFLK",
  "HGBCJFLK",
  "HGBCIFLK",
  "HGBCJFLI",
  "HGBCJFIK",
  "EJBCIHLK",
  "EJBCIGLK",
  "EJBCHGLK",
  "EGBCIHLK",
  "EJBCHGLI",
  "EJBCHGIK",
  "EJBCIFLK",
  "EJBCHFLK",
  "EIBCHFLK",
  "EJBCHFLI",
  "EJBCHFIK",
  "EGBCJFLK",
  "EGBCIFLK",
  "EGBCJFLI",
  "EGBCJFIK",
  "EGBCHFLK",
  "HGBCJFLE",
  "HGBCJFEK",
  "EGBCHFLI",
  "EGBCHFIK",
  "HGBCJFEI",
  "HJBCIDLK",
  "IGBCJDLK",
  "HGBCJDLK",
  "HGBCIDLK",
  "HGBCJDLI",
  "HGBCJDIK",
  "CJBDIFLK",
  "CJBDHFLK",
  "CIBDHFLK",
  "CJBDHFLI",
  "CJBDHFIK",
  "CGBDJFLK",
  "CGBDIFLK",
  "CGBDJFLI",
  "CGBDJFIK",
  "CGBDHFLK",
  "CGBDHFLJ",
  "HGBCJFDK",
  "CGBDHFLI",
  "CGBDHFIK",
  "HGBCJFDI",
  "EJBCIDLK",
  "EJBCHDLK",
  "EIBCHDLK",
  "EJBCHDLI",
  "EJBCHDIK",
  "EGBCJDLK",
  "EGBCIDLK",
  "EGBCJDLI",
  "EGBCJDIK",
  "EGBCHDLK",
  "HGBCJDLE",
  "HGBCJDEK",
  "EGBCHDLI",
  "EGBCHDIK",
  "HGBCJDEI",
  "CJBDEFLK",
  "CEBDIFLK",
  "CJBDEFLI",
  "CJBDEFIK",
  "CEBDHFLK",
  "CJBDHFLE",
  "CJBDHFEK",
  "CEBDHFLI",
  "CEBDHFIK",
  "CJBDHFEI",
  "CGBDEFLK",
  "CGBDJFLE",
  "CGBDJFEK",
  "CGBDEFLI",
  "CGBDEFIK",
  "CGBDJFEI",
  "CGBDHFLE",
  "CGBDHFEK",
  "HGBCJFDE",
  "CGBDHFEI",
  "HJIFAGLK",
  "EJIAHGLK",
  "EJIFAHLK",
  "EJIFAGLK",
  "EGJFAHLK",
  "EGIFAHLK",
  "EGJFAHLI",
  "EGJFAHIK",
  "HJIDAGLK",
  "HJIDAFLK",
  "IGJDAFLK",
  "HGJDAFLK",
  "HGIDAFLK",
  "HGJDAFLI",
  "HGJDAFIK",
  "EJIDAHLK",
  "EJIDAGLK",
  "EGJDAHLK",
  "EGIDAHLK",
  "EGJDAHLI",
  "EGJDAHIK",
  "EJIDAFLK",
  "HJEDAFLK",
  "HEIDAFLK",
  "HJEDAFLI",
  "HJEDAFIK",
  "EGJDAFLK",
  "EGIDAFLK",
  "EGJDAFLI",
  "EGJDAFIK",
  "HGEDAFLK",
  "HGJDAFLE",
  "HGJDAFEK",
  "HGEDAFLI",
  "HGEDAFIK",
  "HGJDAFEI",
  "HJICAGLK",
  "HJICAFLK",
  "IGJCAFLK",
  "HGJCAFLK",
  "HGICAFLK",
  "HGJCAFLI",
  "HGJCAFIK",
  "EJICAHLK",
  "EJICAGLK",
  "EGJCAHLK",
  "EGICAHLK",
  "EGJCAHLI",
  "EGJCAHIK",
  "EJICAFLK",
  "HJECAFLK",
  "HEICAFLK",
  "HJECAFLI",
  "HJECAFIK",
  "EGJCAFLK",
  "EGICAFLK",
  "EGJCAFLI",
  "EGJCAFIK",
  "HGECAFLK",
  "HGJCAFLE",
  "HGJCAFEK",
  "HGECAFLI",
  "HGECAFIK",
  "HGJCAFEI",
  "HJICADLK",
  "IGJCADLK",
  "HGJCADLK",
  "HGICADLK",
  "HGJCADLI",
  "HGJCADIK",
  "CJIDAFLK",
  "HJFCADLK",
  "HFICADLK",
  "HJFCADLI",
  "HJFCADIK",
  "CGJDAFLK",
  "CGIDAFLK",
  "CGJDAFLI",
  "CGJDAFIK",
  "HGFCADLK",
  "CGJDAFLH",
  "HGJCAFDK",
  "HGFCADLI",
  "HGFCADIK",
  "HGJCAFDI",
  "EJICADLK",
  "HJECADLK",
  "HEICADLK",
  "HJECADLI",
  "HJECADIK",
  "EGJCADLK",
  "EGICADLK",
  "EGJCADLI",
  "EGJCADIK",
  "HGECADLK",
  "HGJCADLE",
  "HGJCADEK",
  "HGECADLI",
  "HGECADIK",
  "HGJCADEI",
  "CJEDAFLK",
  "CEIDAFLK",
  "CJEDAFLI",
  "CJEDAFIK",
  "HEFCADLK",
  "HJFCADLE",
  "HJECAFDK",
  "HEFCADLI",
  "HEFCADIK",
  "HJECAFDI",
  "CGEDAFLK",
  "CGJDAFLE",
  "CGJDAFEK",
  "CGEDAFLI",
  "CGEDAFIK",
  "CGJDAFEI",
  "HGFCADLE",
  "HGECAFDK",
  "HGJCAFDE",
  "HGECAFDI",
  "HJBAIGLK",
  "HJBAIFLK",
  "IJBFAGLK",
  "HJBFAGLK",
  "HGBAIFLK",
  "HJBFAGLI",
  "HJBFAGIK",
  "EJBAIHLK",
  "EJBAIGLK",
  "EJBAHGLK",
  "EGBAIHLK",
  "EJBAHGLI",
  "EJBAHGIK",
  "EJBAIFLK",
  "EJBFAHLK",
  "EIBFAHLK",
  "EJBFAHLI",
  "EJBFAHIK",
  "EJBFAGLK",
  "EGBAIFLK",
  "EJBFAGLI",
  "EJBFAGIK",
  "EGBFAHLK",
  "HJBFAGLE",
  "HJBFAGEK",
  "EGBFAHLI",
  "EGBFAHIK",
  "HJBFAGEI",
  "IJBDAHLK",
  "IJBDAGLK",
  "HJBDAGLK",
  "IGBDAHLK",
  "HJBDAGLI",
  "HJBDAGIK",
  "IJBDAFLK",
  "HJBDAFLK",
  "HIBDAFLK",
  "HJBDAFLI",
  "HJBDAFIK",
  "FJBDAGLK",
  "IGBDAFLK",
  "FJBDAGLI",
  "FJBDAGIK",
  "HGBDAFLK",
  "HGBDAFLJ",
  "HGBDAFJK",
  "HGBDAFLI",
  "HGBDAFIK",
  "HGBDAFIJ",
  "EJBAIDLK",
  "EJBDAHLK",
  "EIBDAHLK",
  "EJBDAHLI",
  "EJBDAHIK",
  "EJBDAGLK",
  "EGBAIDLK",
  "EJBDAGLI",
  "EJBDAGIK",
  "EGBDAHLK",
  "HJBDAGLE",
  "HJBDAGEK",
  "EGBDAHLI",
  "EGBDAHIK",
  "HJBDAGEI",
  "EJBDAFLK",
  "EIBDAFLK",
  "EJBDAFLI",
  "EJBDAFIK",
  "HEBDAFLK",
  "HJBDAFLE",
  "HJBDAFEK",
  "HEBDAFLI",
  "HEBDAFIK",
  "HJBDAFEI",
  "EGBDAFLK",
  "EGBDAFLJ",
  "EGBDAFJK",
  "EGBDAFLI",
  "EGBDAFIK",
  "EGBDAFIJ",
  "HGBDAFLE",
  "HGBDAFEK",
  "HGBDAFEJ",
  "HGBDAFEI",
  "IJBCAHLK",
  "IJBCAGLK",
  "HJBCAGLK",
  "IGBCAHLK",
  "HJBCAGLI",
  "HJBCAGIK",
  "IJBCAFLK",
  "HJBCAFLK",
  "HIBCAFLK",
  "HJBCAFLI",
  "HJBCAFIK",
  "CJBFAGLK",
  "IGBCAFLK",
  "CJBFAGLI",
  "CJBFAGIK",
  "HGBCAFLK",
  "HGBCAFLJ",
  "HGBCAFJK",
  "HGBCAFLI",
  "HGBCAFIK",
  "HGBCAFIJ",
  "EJBAICLK",
  "EJBCAHLK",
  "EIBCAHLK",
  "EJBCAHLI",
  "EJBCAHIK",
  "EJBCAGLK",
  "EGBAICLK",
  "EJBCAGLI",
  "EJBCAGIK",
  "EGBCAHLK",
  "HJBCAGLE",
  "HJBCAGEK",
  "EGBCAHLI",
  "EGBCAHIK",
  "HJBCAGEI",
  "EJBCAFLK",
  "EIBCAFLK",
  "EJBCAFLI",
  "EJBCAFIK",
  "HEBCAFLK",
  "HJBCAFLE",
  "HJBCAFEK",
  "HEBCAFLI",
  "HEBCAFIK",
  "HJBCAFEI",
  "EGBCAFLK",
  "EGBCAFLJ",
  "EGBCAFJK",
  "EGBCAFLI",
  "EGBCAFIK",
  "EGBCAFIJ",
  "HGBCAFLE",
  "HGBCAFEK",
  "HGBCAFEJ",
  "HGBCAFEI",
  "IJBCADLK",
  "HJBCADLK",
  "HIBCADLK",
  "HJBCADLI",
  "HJBCADIK",
  "CJBDAGLK",
  "IGBCADLK",
  "CJBDAGLI",
  "CJBDAGIK",
  "HGBCADLK",
  "HGBCADLJ",
  "HGBCADJK",
  "HGBCADLI",
  "HGBCADIK",
  "HGBCADIJ",
  "CJBDAFLK",
  "CIBDAFLK",
  "CJBDAFLI",
  "CJBDAFIK",
  "HFBCADLK",
  "CJBDAFLH",
  "HJBCAFDK",
  "HFBCADLI",
  "HFBCADIK",
  "HJBCAFDI",
  "CGBDAFLK",
  "CGBDAFLJ",
  "CGBDAFJK",
  "CGBDAFLI",
  "CGBDAFIK",
  "CGBDAFIJ",
  "CGBDAFLH",
  "HGBCAFDK",
  "HGBCAFDJ",
  "HGBCAFDI",
  "EJBCADLK",
  "EIBCADLK",
  "EJBCADLI",
  "EJBCADIK",
  "HEBCADLK",
  "HJBCADLE",
  "HJBCADEK",
  "HEBCADLI",
  "HEBCADIK",
  "HJBCADEI",
  "EGBCADLK",
  "EGBCADLJ",
  "EGBCADJK",
  "EGBCADLI",
  "EGBCADIK",
  "EGBCADIJ",
  "HGBCADLE",
  "HGBCADEK",
  "HGBCADEJ",
  "HGBCADEI",
  "CEBDAFLK",
  "CJBDAFLE",
  "CJBDAFEK",
  "CEBDAFLI",
  "CEBDAFIK",
  "CJBDAFEI",
  "HFBCADLE",
  "HEBCAFDK",
  "HJBCAFDE",
  "HEBCAFDI",
  "CGBDAFLE",
  "CGBDAFEK",
  "CGBDAFEJ",
  "CGBDAFEI",
  "HGBCAFDE",
];

export const THIRD_PLACE_MATCH_WINNERS = {
  73: "E", 76: "I", 78: "A", 79: "L",
  80: "D", 81: "G", 84: "B", 86: "K",
};

const THIRD_LOOKUP = new Map();
for (const letters of ANNEX_C_ROWS) {
  const combo = letters.split("").sort().join("");
  const byWinner = {};
  for (let i = 0; i < ANNEX_C_WINNERS.length; i++) {
    byWinner[ANNEX_C_WINNERS[i]] = letters[i];
  }
  THIRD_LOOKUP.set(combo, byWinner);
}

const GROUP_LETTERS = "ABCDEFGHIJKL";

export function isGroupStageComplete(standings) {
  for (const letter of GROUP_LETTERS) {
    const rows = standings[`Group ${letter}`];
    if (!rows || rows.length < 3) return false;
    if ((rows[2].p || 0) < 3) return false;
  }
  return true;
}

function standingsThird(standings, letter) {
  const rows = standings[`Group ${letter}`];
  return rows && rows.length >= 3 ? rows[2].team : null;
}

export function pickQualifyingThirds(standings, source) {
  const thirds = [];
  for (const [groupName, rows] of Object.entries(standings)) {
    if (rows.length >= 3) {
      thirds.push({ group: groupName.replace("Group ", ""), row: rows[2] });
    }
  }

  if (source === "wcup2026.org") {
    const ranked = thirds.filter((t) => t.row.qual_rank != null);
    if (ranked.length >= 8) {
      ranked.sort((a, b) => a.row.qual_rank - b.row.qual_rank);
      return ranked.slice(0, 8);
    }
  }

  thirds.sort(
    (a, b) =>
      b.row.pts - a.row.pts ||
      b.row.gd - a.row.gd ||
      b.row.gf - a.row.gf,
  );
  return thirds.slice(0, 8);
}

export function thirdPlaceAssignment(standings, source) {
  if (!isGroupStageComplete(standings)) return null;
  const qual = pickQualifyingThirds(standings, source);
  if (qual.length < 8) return null;
  const combo = qual.map((q) => q.group).sort().join("");
  return THIRD_LOOKUP.get(combo) || null;
}

export function resolveThirdPlaceCode(code, standings, matchId, source) {
  if (!code || !code.startsWith("3")) return null;
  if (code.length === 2 && /[A-L]/.test(code[1])) {
    return standingsThird(standings, code[1]);
  }
  if (code.includes("/")) {
    if (!isGroupStageComplete(standings)) return null;
    const assignment = thirdPlaceAssignment(standings, source);
    if (!assignment || matchId == null) return null;
    const winner = THIRD_PLACE_MATCH_WINNERS[matchId];
    if (!winner || !assignment[winner]) return null;
    const groupLetter = assignment[winner];
    const eligible = new Set(code.slice(1).split("/"));
    if (!eligible.has(groupLetter)) return null;
    return standingsThird(standings, groupLetter);
  }
  return null;
}

export function formatThirdPlaceholder(code) {
  if (code.startsWith("3") && code.includes("/")) return `3rd (${code.slice(1)})`;
  if (code.length === 2 && code.startsWith("3")) return `3rd Group ${code[1]}`;
  return code;
}
