"""FIFA World Cup 2026 Annex C third-place assignment lookup."""

ANNEX_C_WINNERS = ["A", "B", "D", "E", "G", "I", "K", "L"]

ANNEX_C_ROWS = [
    "EJIFHGLK",
    "HGIDJFLK",
    "EJIDHGLK",
    "EJIDHFLK",
    "EGIDJFLK",
    "EGJDHFLK",
    "EGIDHFLK",
    "EGJDHFLI",
    "EGJDHFIK",
    "HGICJFLK",
    "EJICHGLK",
    "EJICHFLK",
    "EGICJFLK",
    "EGJCHFLK",
    "EGICHFLK",
    "EGJCHFLI",
    "EGJCHFIK",
    "HGICJDLK",
    "CJIDHFLK",
    "CGIDJFLK",
    "CGJDHFLK",
    "CGIDHFLK",
    "CGJDHFLI",
    "CGJDHFIK",
    "EJICHDLK",
    "EGICJDLK",
    "EGJCHDLK",
    "EGICHDLK",
    "EGJCHDLI",
    "EGJCHDIK",
    "CJEDIFLK",
    "CJEDHFLK",
    "CEIDHFLK",
    "CJEDHFLI",
    "CJEDHFIK",
    "CGEDJFLK",
    "CGEDIFLK",
    "CGEDJFLI",
    "CGEDJFIK",
    "CGEDHFLK",
    "CGJDHFLE",
    "CGJDHFEK",
    "CGEDHFLI",
    "CGEDHFIK",
    "CGJDHFEI",
    "HJBFIGLK",
    "EJIBHGLK",
    "EJBFIHLK",
    "EJBFIGLK",
    "EJBFHGLK",
    "EGBFIHLK",
    "EJBFHGLI",
    "EJBFHGIK",
    "HJBDIGLK",
    "HJBDIFLK",
    "IGBDJFLK",
    "HGBDJFLK",
    "HGBDIFLK",
    "HGBDJFLI",
    "HGBDJFIK",
    "EJBDIHLK",
    "EJBDIGLK",
    "EJBDHGLK",
    "EGBDIHLK",
    "EJBDHGLI",
    "EJBDHGIK",
    "EJBDIFLK",
    "EJBDHFLK",
    "EIBDHFLK",
    "EJBDHFLI",
    "EJBDHFIK",
    "EGBDJFLK",
    "EGBDIFLK",
    "EGBDJFLI",
    "EGBDJFIK",
    "EGBDHFLK",
    "HGBDJFLE",
    "HGBDJFEK",
    "EGBDHFLI",
    "EGBDHFIK",
    "HGBDJFEI",
    "HJBCIGLK",
    "HJBCIFLK",
    "IGBCJFLK",
    "HGBCJFLK",
    "HGBCIFLK",
    "HGBCJFLI",
    "HGBCJFIK",
    "EJBCIHLK",
    "EJBCIGLK",
    "EJBCHGLK",
    "EGBCIHLK",
    "EJBCHGLI",
    "EJBCHGIK",
    "EJBCIFLK",
    "EJBCHFLK",
    "EIBCHFLK",
    "EJBCHFLI",
    "EJBCHFIK",
    "EGBCJFLK",
    "EGBCIFLK",
    "EGBCJFLI",
    "EGBCJFIK",
    "EGBCHFLK",
    "HGBCJFLE",
    "HGBCJFEK",
    "EGBCHFLI",
    "EGBCHFIK",
    "HGBCJFEI",
    "HJBCIDLK",
    "IGBCJDLK",
    "HGBCJDLK",
    "HGBCIDLK",
    "HGBCJDLI",
    "HGBCJDIK",
    "CJBDIFLK",
    "CJBDHFLK",
    "CIBDHFLK",
    "CJBDHFLI",
    "CJBDHFIK",
    "CGBDJFLK",
    "CGBDIFLK",
    "CGBDJFLI",
    "CGBDJFIK",
    "CGBDHFLK",
    "CGBDHFLJ",
    "HGBCJFDK",
    "CGBDHFLI",
    "CGBDHFIK",
    "HGBCJFDI",
    "EJBCIDLK",
    "EJBCHDLK",
    "EIBCHDLK",
    "EJBCHDLI",
    "EJBCHDIK",
    "EGBCJDLK",
    "EGBCIDLK",
    "EGBCJDLI",
    "EGBCJDIK",
    "EGBCHDLK",
    "HGBCJDLE",
    "HGBCJDEK",
    "EGBCHDLI",
    "EGBCHDIK",
    "HGBCJDEI",
    "CJBDEFLK",
    "CEBDIFLK",
    "CJBDEFLI",
    "CJBDEFIK",
    "CEBDHFLK",
    "CJBDHFLE",
    "CJBDHFEK",
    "CEBDHFLI",
    "CEBDHFIK",
    "CJBDHFEI",
    "CGBDEFLK",
    "CGBDJFLE",
    "CGBDJFEK",
    "CGBDEFLI",
    "CGBDEFIK",
    "CGBDJFEI",
    "CGBDHFLE",
    "CGBDHFEK",
    "HGBCJFDE",
    "CGBDHFEI",
    "HJIFAGLK",
    "EJIAHGLK",
    "EJIFAHLK",
    "EJIFAGLK",
    "EGJFAHLK",
    "EGIFAHLK",
    "EGJFAHLI",
    "EGJFAHIK",
    "HJIDAGLK",
    "HJIDAFLK",
    "IGJDAFLK",
    "HGJDAFLK",
    "HGIDAFLK",
    "HGJDAFLI",
    "HGJDAFIK",
    "EJIDAHLK",
    "EJIDAGLK",
    "EGJDAHLK",
    "EGIDAHLK",
    "EGJDAHLI",
    "EGJDAHIK",
    "EJIDAFLK",
    "HJEDAFLK",
    "HEIDAFLK",
    "HJEDAFLI",
    "HJEDAFIK",
    "EGJDAFLK",
    "EGIDAFLK",
    "EGJDAFLI",
    "EGJDAFIK",
    "HGEDAFLK",
    "HGJDAFLE",
    "HGJDAFEK",
    "HGEDAFLI",
    "HGEDAFIK",
    "HGJDAFEI",
    "HJICAGLK",
    "HJICAFLK",
    "IGJCAFLK",
    "HGJCAFLK",
    "HGICAFLK",
    "HGJCAFLI",
    "HGJCAFIK",
    "EJICAHLK",
    "EJICAGLK",
    "EGJCAHLK",
    "EGICAHLK",
    "EGJCAHLI",
    "EGJCAHIK",
    "EJICAFLK",
    "HJECAFLK",
    "HEICAFLK",
    "HJECAFLI",
    "HJECAFIK",
    "EGJCAFLK",
    "EGICAFLK",
    "EGJCAFLI",
    "EGJCAFIK",
    "HGECAFLK",
    "HGJCAFLE",
    "HGJCAFEK",
    "HGECAFLI",
    "HGECAFIK",
    "HGJCAFEI",
    "HJICADLK",
    "IGJCADLK",
    "HGJCADLK",
    "HGICADLK",
    "HGJCADLI",
    "HGJCADIK",
    "CJIDAFLK",
    "HJFCADLK",
    "HFICADLK",
    "HJFCADLI",
    "HJFCADIK",
    "CGJDAFLK",
    "CGIDAFLK",
    "CGJDAFLI",
    "CGJDAFIK",
    "HGFCADLK",
    "CGJDAFLH",
    "HGJCAFDK",
    "HGFCADLI",
    "HGFCADIK",
    "HGJCAFDI",
    "EJICADLK",
    "HJECADLK",
    "HEICADLK",
    "HJECADLI",
    "HJECADIK",
    "EGJCADLK",
    "EGICADLK",
    "EGJCADLI",
    "EGJCADIK",
    "HGECADLK",
    "HGJCADLE",
    "HGJCADEK",
    "HGECADLI",
    "HGECADIK",
    "HGJCADEI",
    "CJEDAFLK",
    "CEIDAFLK",
    "CJEDAFLI",
    "CJEDAFIK",
    "HEFCADLK",
    "HJFCADLE",
    "HJECAFDK",
    "HEFCADLI",
    "HEFCADIK",
    "HJECAFDI",
    "CGEDAFLK",
    "CGJDAFLE",
    "CGJDAFEK",
    "CGEDAFLI",
    "CGEDAFIK",
    "CGJDAFEI",
    "HGFCADLE",
    "HGECAFDK",
    "HGJCAFDE",
    "HGECAFDI",
    "HJBAIGLK",
    "HJBAIFLK",
    "IJBFAGLK",
    "HJBFAGLK",
    "HGBAIFLK",
    "HJBFAGLI",
    "HJBFAGIK",
    "EJBAIHLK",
    "EJBAIGLK",
    "EJBAHGLK",
    "EGBAIHLK",
    "EJBAHGLI",
    "EJBAHGIK",
    "EJBAIFLK",
    "EJBFAHLK",
    "EIBFAHLK",
    "EJBFAHLI",
    "EJBFAHIK",
    "EJBFAGLK",
    "EGBAIFLK",
    "EJBFAGLI",
    "EJBFAGIK",
    "EGBFAHLK",
    "HJBFAGLE",
    "HJBFAGEK",
    "EGBFAHLI",
    "EGBFAHIK",
    "HJBFAGEI",
    "IJBDAHLK",
    "IJBDAGLK",
    "HJBDAGLK",
    "IGBDAHLK",
    "HJBDAGLI",
    "HJBDAGIK",
    "IJBDAFLK",
    "HJBDAFLK",
    "HIBDAFLK",
    "HJBDAFLI",
    "HJBDAFIK",
    "FJBDAGLK",
    "IGBDAFLK",
    "FJBDAGLI",
    "FJBDAGIK",
    "HGBDAFLK",
    "HGBDAFLJ",
    "HGBDAFJK",
    "HGBDAFLI",
    "HGBDAFIK",
    "HGBDAFIJ",
    "EJBAIDLK",
    "EJBDAHLK",
    "EIBDAHLK",
    "EJBDAHLI",
    "EJBDAHIK",
    "EJBDAGLK",
    "EGBAIDLK",
    "EJBDAGLI",
    "EJBDAGIK",
    "EGBDAHLK",
    "HJBDAGLE",
    "HJBDAGEK",
    "EGBDAHLI",
    "EGBDAHIK",
    "HJBDAGEI",
    "EJBDAFLK",
    "EIBDAFLK",
    "EJBDAFLI",
    "EJBDAFIK",
    "HEBDAFLK",
    "HJBDAFLE",
    "HJBDAFEK",
    "HEBDAFLI",
    "HEBDAFIK",
    "HJBDAFEI",
    "EGBDAFLK",
    "EGBDAFLJ",
    "EGBDAFJK",
    "EGBDAFLI",
    "EGBDAFIK",
    "EGBDAFIJ",
    "HGBDAFLE",
    "HGBDAFEK",
    "HGBDAFEJ",
    "HGBDAFEI",
    "IJBCAHLK",
    "IJBCAGLK",
    "HJBCAGLK",
    "IGBCAHLK",
    "HJBCAGLI",
    "HJBCAGIK",
    "IJBCAFLK",
    "HJBCAFLK",
    "HIBCAFLK",
    "HJBCAFLI",
    "HJBCAFIK",
    "CJBFAGLK",
    "IGBCAFLK",
    "CJBFAGLI",
    "CJBFAGIK",
    "HGBCAFLK",
    "HGBCAFLJ",
    "HGBCAFJK",
    "HGBCAFLI",
    "HGBCAFIK",
    "HGBCAFIJ",
    "EJBAICLK",
    "EJBCAHLK",
    "EIBCAHLK",
    "EJBCAHLI",
    "EJBCAHIK",
    "EJBCAGLK",
    "EGBAICLK",
    "EJBCAGLI",
    "EJBCAGIK",
    "EGBCAHLK",
    "HJBCAGLE",
    "HJBCAGEK",
    "EGBCAHLI",
    "EGBCAHIK",
    "HJBCAGEI",
    "EJBCAFLK",
    "EIBCAFLK",
    "EJBCAFLI",
    "EJBCAFIK",
    "HEBCAFLK",
    "HJBCAFLE",
    "HJBCAFEK",
    "HEBCAFLI",
    "HEBCAFIK",
    "HJBCAFEI",
    "EGBCAFLK",
    "EGBCAFLJ",
    "EGBCAFJK",
    "EGBCAFLI",
    "EGBCAFIK",
    "EGBCAFIJ",
    "HGBCAFLE",
    "HGBCAFEK",
    "HGBCAFEJ",
    "HGBCAFEI",
    "IJBCADLK",
    "HJBCADLK",
    "HIBCADLK",
    "HJBCADLI",
    "HJBCADIK",
    "CJBDAGLK",
    "IGBCADLK",
    "CJBDAGLI",
    "CJBDAGIK",
    "HGBCADLK",
    "HGBCADLJ",
    "HGBCADJK",
    "HGBCADLI",
    "HGBCADIK",
    "HGBCADIJ",
    "CJBDAFLK",
    "CIBDAFLK",
    "CJBDAFLI",
    "CJBDAFIK",
    "HFBCADLK",
    "CJBDAFLH",
    "HJBCAFDK",
    "HFBCADLI",
    "HFBCADIK",
    "HJBCAFDI",
    "CGBDAFLK",
    "CGBDAFLJ",
    "CGBDAFJK",
    "CGBDAFLI",
    "CGBDAFIK",
    "CGBDAFIJ",
    "CGBDAFLH",
    "HGBCAFDK",
    "HGBCAFDJ",
    "HGBCAFDI",
    "EJBCADLK",
    "EIBCADLK",
    "EJBCADLI",
    "EJBCADIK",
    "HEBCADLK",
    "HJBCADLE",
    "HJBCADEK",
    "HEBCADLI",
    "HEBCADIK",
    "HJBCADEI",
    "EGBCADLK",
    "EGBCADLJ",
    "EGBCADJK",
    "EGBCADLI",
    "EGBCADIK",
    "EGBCADIJ",
    "HGBCADLE",
    "HGBCADEK",
    "HGBCADEJ",
    "HGBCADEI",
    "CEBDAFLK",
    "CJBDAFLE",
    "CJBDAFEK",
    "CEBDAFLI",
    "CEBDAFIK",
    "CJBDAFEI",
    "HFBCADLE",
    "HEBCAFDK",
    "HJBCAFDE",
    "HEBCAFDI",
    "CGBDAFLE",
    "CGBDAFEK",
    "CGBDAFEJ",
    "CGBDAFEI",
    "HGBCAFDE",
]

THIRD_PLACE_MATCH_WINNERS = {
    73: "E", 76: "I", 78: "A", 79: "L",
    80: "D", 81: "G", 84: "B", 86: "K",
}


def _build_lookup():
    table = {}
    for letters in ANNEX_C_ROWS:
        combo = "".join(sorted(letters))
        table[combo] = {ANNEX_C_WINNERS[i]: letters[i] for i in range(8)}
    return table


_THIRD_LOOKUP = _build_lookup()


GROUP_LETTERS = "ABCDEFGHIJKL"


def is_group_stage_complete(standings):
    """True when every group has played 3 matchdays (third row p >= 3)."""
    for letter in GROUP_LETTERS:
        rows = standings.get(f"Group {letter}", [])
        if len(rows) < 3:
            return False
        if rows[2].get("p", 0) < 3:
            return False
    return True


def pick_qualifying_thirds(standings, source=None):
    thirds = []
    for group_name, rows in standings.items():
        if len(rows) >= 3:
            letter = group_name.replace("Group ", "")
            thirds.append({"group": letter, "row": rows[2]})

    if source == "wcup2026.org":
        ranked = [t for t in thirds if t["row"].get("qual_rank") is not None]
        if len(ranked) >= 8:
            ranked.sort(key=lambda t: t["row"]["qual_rank"])
            return ranked[:8]

    thirds.sort(key=lambda t: (-t["row"]["pts"], -t["row"]["gd"], -t["row"]["gf"]))
    return thirds[:8]


def third_place_assignment(standings, source=None):
    if not is_group_stage_complete(standings):
        return None
    qual = pick_qualifying_thirds(standings, source=source)
    if len(qual) < 8:
        return None
    combo = "".join(sorted(q["group"] for q in qual))
    return _THIRD_LOOKUP.get(combo)


def resolve_third_place_code(code, standings, match_id=None, source=None):
    if not code or not code.startswith("3"):
        return None
    if len(code) == 2 and code[1].isalpha():
        return _standings_third(standings, code[1])
    if "/" in code:
        if not is_group_stage_complete(standings):
            return None
        assignment = third_place_assignment(standings, source=source)
        if not assignment or match_id is None:
            return None
        winner = THIRD_PLACE_MATCH_WINNERS.get(match_id)
        if not winner or winner not in assignment:
            return None
        group_letter = assignment[winner]
        eligible = set(code[1:].split("/"))
        if group_letter not in eligible:
            return None
        return _standings_third(standings, group_letter)
    return None


def _standings_third(standings, letter):
    rows = standings.get(f"Group {letter}", [])
    return rows[2]["team"] if len(rows) >= 3 else None


def format_third_placeholder(code):
    if code.startswith("3") and "/" in code:
        return f"3rd ({code[1:]})"
    if len(code) == 2 and code.startswith("3"):
        return f"3rd Group {code[1]}"
    return code
